[server]
listen = "0.0.0.0"
port = 6380
tls_listen = "0.0.0.0"
tls_port = 6443
tls_key_file = ""
tls_cert_file = ""
tls_auth_client = false
tls_ca_cert_file = ""
pd_addrs = "127.0.0.1:2379"
instance_id = "1"
prometheus_listen = "0.0.0.0"
prometheus_port = 8080
log_level = "info"
log_file = "tikv-service.log"

[backend]
use_async_commit = true
try_one_pc_commit = true
use_pessimistic_txn = false
local_pool_number = 8
txn_retry_count = 2
txn_region_backoff_delay_ms = 2
txn_region_backoff_delay_attemps = 5
txn_lock_backoff_delay_ms = 2
txn_lock_backoff_delay_attemps = 5

completion_queue_size = 1
grpc_keepalive_time = 10000
grpc_keepalive_timeout = 2000
allow_batch = true
max_batch_wait_time = 10
max_batch_size = 20
max_inflight_requests = 10000
