name: Continuous Integration
on: [push, pull_request]

# Concurrency ensures that only a single job or workflow using the same concurrency group will run at a time.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check, Fmt, Clippy, Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.4.0

      - uses: actions-rs/cargo@v1
        with:
          command: check

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all --all-targets -- -D warnings

      - uses: actions-rs/cargo@v1
        with:
          command: test

  e2e-test:
    name: E2E Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.GIT_ACTION_BOT }}
        run: git config --global url."https://${TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: Setup tikv instance
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh
          /home/runner/.tiup/bin/tiup playground nightly --mode tikv-slim --without-monitor &

      - name: Setup tidis
        run: |
          cargo build
          ./target/debug/tidis-server --config="config.toml" &

      - name: Setup test tool env
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Setup test tool dependency
        working-directory: test
        run: pip install -r requirements.txt

      - name: Run E2E test
        working-directory: test
        run: python test_helper.py --port 6666
